# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Charts'
  pod 'JWTDecode', '~> 2.4'

  target 'testProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testProjectUITests' do
    # Pods for testing
  end

end